name: py310
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - _python_abi3_support=1.0
  - absl-py=2.3.1
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - aom=3.6.0
  - arrow-cpp=13.0.0
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=25.3.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - blas=2.134
  - blas-devel=3.9.0
  - boost-cpp=1.82.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - colorama=0.4.6
  - contourpy=1.3.1
  - cpython=3.10.18
  - cuda-version=11.8
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - datasets=2.19.2
  - dav1d=1.2.1
  - dill=0.3.8
  - et_xmlfile=1.1.0
  - expat=2.7.1
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.7.0
  - gflags=2.2.2
  - glog=0.7.1
  - graphite2=1.3.14
  - h2=4.2.0
  - harfbuzz=10.2.0
  - hf-xet=1.1.8
  - hpack=4.1.0
  - huggingface_hub=0.34.4
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.10
  - intel-openmp=2025.0.0
  - joblib=1.5.1
  - jpeg=9e
  - kiwisolver=1.4.8
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=13.0.0
  - libavif=1.1.1
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcups=2.4.2
  - libcurl=8.14.1
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgpg-error=1.55
  - libgrpc=1.62.2
  - libhwloc=2.12.1
  - libiconv=1.16
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.57.0
  - libnl=3.11.0
  - libopenblas=0.3.30
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=256.9
  - libthrift=0.19.0
  - libtiff=4.7.0
  - libudev1=257.4
  - libutf8proc=2.8.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxgboost=2.1.3
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.2.13
  - llvm-openmp=20.1.8
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mesalib=25.1.5
  - mkl=2024.2.2
  - mkl-service=2.5.2
  - mkl_fft=2.0.0
  - mkl_random=1.2.10
  - multidict=6.6.3
  - multiprocess=0.70.16
  - mysql=8.4.0
  - nccl=2.27.3.1
  - ncurses=6.5
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.30
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openpyxl=3.1.5
  - openssl=3.5.2
  - orc=2.0.1
  - packaging=25.0
  - pandas=2.2.3
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.46.4
  - propcache=0.3.1
  - pthread-stubs=0.3
  - py-xgboost=2.1.3
  - pyarrow=13.0.0
  - pyarrow-hotfix=0.7
  - pycparser=2.22
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-gil=3.10.18
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.2
  - pytorch-cpu
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - rdma-core=55.0
  - re2=2023.09.01
  - readline=8.3
  - regex=2025.7.34
  - requests=2.32.5
  - s2n=1.4.15
  - safetensors=0.6.2
  - scikit-learn=1.7.1
  - scipy=1.15.2
  - setuptools=78.1.1
  - sip=6.10.0
  - six=1.17.0
  - snappy=1.2.2
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - tabulate=0.9.0
  - tbb=2021.13.0
  - tbb-devel=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - tokenizers=0.21.4
  - tomli=2.2.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - transformers=4.53.0
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - ucx=1.16.0
  - unicodedata2=15.1.0
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xgboost=2.1.3
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xxhash=0.8.3
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.20.1
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - astunparse==1.6.3
      - filelock==3.13.1
      - flatbuffers==25.2.10
      - fsspec==2024.6.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.14.0
      - imbalanced-learn==0.14.0
      - imblearn==0.0
      - jinja2==3.1.4
      - keras==3.11.3
      - libclang==18.1.1
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - namex==0.1.0
      - networkx==3.3
      - opt-einsum==3.4.0
      - optree==0.17.0
      - protobuf==4.25.8
      - pygments==2.19.2
      - rich==14.1.0
      - sympy==1.13.3
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - werkzeug==3.1.3
      - wrapt==1.17.3
